[auth]
enabled = true
site_url = "https://covera-app-navy.vercel.app"
additional_redirect_urls = [
  "https://covera-app-navy.vercel.app",
  "https://covera-app-navy.vercel.app/auth/callback",
  "http://localhost:3000",
  "http://localhost:3000/auth/callback"
]
jwt_expiry = 99999
