export interface EmailProps {
  name: string;
  email: string;
}

export interface ConfirmationProps extends EmailProps {
  confirmationUrl: string;
}

export interface ResetPasswordProps extends EmailProps {
  resetUrl: string;
}

export const ConfirmationEmail = ({ name, email, confirmationUrl }: ConfirmationProps) => ({
  subject: 'Confirmez votre adresse email — Covera',
  html: `<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Confirmez votre email — Covera</title></head><body style="margin:0;padding:0;background:#f8fafc;font-family:ui-sans-serif,system-ui,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.06);"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:40px;text-align:center;"><h1 style="color:#fff;font-size:28px;font-weight:800;margin:0;">Covera</h1><p style="color:rgba(255,255,255,0.85);font-size:14px;margin:8px 0 0;">Tes assurances, clarifiées.</p></td></tr><tr><td style="padding:40px;"><p style="font-size:16px;color:#334155;margin:0 0 8px;">Bonjour ${name || email},</p><p style="font-size:15px;color:#475569;margin:0 0 28px;line-height:1.6;">Vous avez créé un compte Covera. Cliquez sur le bouton ci-dessous pour confirmer votre adresse email et activer votre compte.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);border-radius:12px;text-align:center;"><a href="${confirmationUrl}" style="display:block;padding:16px 40px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">Confirmer mon email</a></td></tr></table><p style="font-size:13px;color:#94a3b8;margin:24px 0 0;text-align:center;line-height:1.6;">Ce lien expire dans 1 heure. Si vous n'avez pas créé de compte Covera, ignorez ce message.</p></td></tr><tr><td style="padding:20px 40px;background:#f8fafc;border-top:1px solid #f1f5f9;text-align:center;"><p style="font-size:12px;color:#94a3b8;margin:0;">© 2026 Covera · covera.app</p></td></tr></table></td></tr></table></body></html>`,
});

export const ResetPasswordEmail = ({ name, email, resetUrl }: ResetPasswordProps) => ({
  subject: 'Réinitialisez votre mot de passe — Covera',
  html: `<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Réinitialisation mot de passe — Covera</title></head><body style="margin:0;padding:0;background:#f8fafc;font-family:ui-sans-serif,system-ui,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.06);"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:40px;text-align:center;"><h1 style="color:#fff;font-size:28px;font-weight:800;margin:0;">Covera</h1><p style="color:rgba(255,255,255,0.85);font-size:14px;margin:8px 0 0;">Tes assurances, clarifiées.</p></td></tr><tr><td style="padding:40px;"><p style="font-size:16px;color:#334155;margin:0 0 8px;">Bonjour ${name || email},</p><p style="font-size:15px;color:#475569;margin:0 0 28px;line-height:1.6;">Nous avons reçu une demande de réinitialisation de mot de passe. Cliquez sur le bouton ci-dessous pour définir un nouveau mot de passe.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);border-radius:12px;text-align:center;"><a href="${resetUrl}" style="display:block;padding:16px 40px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">Réinitialiser mon mot de passe</a></td></tr></table><p style="font-size:13px;color:#94a3b8;margin:24px 0 0;text-align:center;line-height:1.6;">Ce lien expire dans 1 heure. Si vous n'avez pas demandé de réinitialisation, ignorez ce message.</p></td></tr><tr><td style="padding:20px 40px;background:#f8fafc;border-top:1px solid #f1f5f9;text-align:center;"><p style="font-size:12px;color:#94a3b8;margin:0;">© 2026 Covera · covera.app</p></td></tr></table></td></tr></table></body></html>`,
});

export const WelcomeEmail = ({ name, email }: EmailProps) => ({
  subject: 'Bienvenue sur Covera 🎉',
  html: `<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Bienvenue sur Covera</title></head><body style="margin:0;padding:0;background:#f8fafc;font-family:ui-sans-serif,system-ui,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.06);"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:40px;text-align:center;"><h1 style="color:#fff;font-size:28px;font-weight:800;margin:0;">Covera 🎉</h1></td></tr><tr><td style="padding:40px;text-align:center;"><h2 style="font-size:24px;font-weight:700;color:#0f172a;margin:0 0 16px;">Bienvenue${name ? `, ${name}` : ''} !</h2><p style="font-size:16px;color:#475569;line-height:1.7;margin:0 0 28px;">Votre compte Covera est actif. Importez vos contrats d'assurance, comprenez exactement ce qui est couvert, et posez vos questions à l'IA.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);border-radius:12px;text-align:center;"><a href="https://covera.app" style="display:block;padding:16px 40px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">Commencer →</a></td></tr></table></td></tr><tr><td style="padding:20px 40px;background:#f8fafc;border-top:1px solid #f1f5f9;text-align:center;"><p style="font-size:12px;color:#94a3b8;margin:0;">© 2026 Covera</p></td></tr></table></td></tr></table></body></html>`,
});
